@startuml

[*] --> NEW
NEW --> COMPLETING
COMPLETING --> NORMAL
COMPLETING --> EXCEPTIONAL

NEW --> CANCELLED
NEW --> INTERRUPTING
INTERRUPTING --> INTERRUPTED

NEW : 状态值 0
COMPLETING : 状态值 1
NORMAL :状态值 2
EXCEPTIONAL : 状态值 3
CANCELLED : 状态值 4
INTERRUPTING : 状态值 5
INTERRUPTED : 状态值 6
@enduml