@startuml
class Director{
    + constructor()
}

abstract class Builder{
    + buildPart()
}

class ConcreteBuilder{
}
class Product{
}

Director *-->Builder
ConcreteBuilder --|>Builder
ConcreteBuilder -->Product
@enduml